GitHub Actions: Fix `wait-for-all-lint` skippable

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -27,9 +27,13 @@ jobs:
       golangci-lint-version: v2.11 # Must be kept in sync with @../../mise.toml
 
   wait-for-all-lint:
+    if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
     needs:
       - actions
       - go
     runs-on: ubuntu-latest
     steps:
-      - run: exit 0
+      - name: Assert no required jobs were cancelled or failed
+        run: |
+          echo "::error::Required jobs have been cancelled or failed!"
+          exit 1
